/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.memberber.rpc.domain

import com.twitter.finagle.Thrift
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{ThriftStruct, TReusableMemoryTransport}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.collection.{Map, Set}

import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class MemberEndpoint$FinagleService(
  iface: MemberEndpoint[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int,
  serviceName: String
) extends com.twitter.finagle.Service[Array[Byte], Array[Byte]] {
  import MemberEndpoint._

  def this(
    iface: MemberEndpoint[Future],
    protocolFactory: TProtocolFactory,
    stats: StatsReceiver,
    maxThriftBufferSize: Int
  ) = this(iface, protocolFactory, stats, maxThriftBufferSize, "MemberEndpoint")

  def this(
    iface: MemberEndpoint[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)

  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_register {
    val RequestsCounter = scopedStats.scope("register").counter("requests")
    val SuccessCounter = scopedStats.scope("register").counter("success")
    val FailuresCounter = scopedStats.scope("register").counter("failures")
    val FailuresScope = scopedStats.scope("register").scope("failures")
  }
  addFunction("register", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_register.RequestsCounter.incr()
      val args = Register.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.register(args.traceId, args.mobileTicket, args.deviceType)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.memberber.rpc.domain.MemberBaseResponse =>
        reply("register", seqid, Register.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_register.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_register.FailuresCounter.incr()
          __stats_register.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("register", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getMemberById {
    val RequestsCounter = scopedStats.scope("getMemberById").counter("requests")
    val SuccessCounter = scopedStats.scope("getMemberById").counter("success")
    val FailuresCounter = scopedStats.scope("getMemberById").counter("failures")
    val FailuresScope = scopedStats.scope("getMemberById").scope("failures")
  }
  addFunction("getMemberById", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getMemberById.RequestsCounter.incr()
      val args = GetMemberById.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getMemberById(args.traceId, args.memberId)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.memberber.rpc.domain.MemberResponse =>
        reply("getMemberById", seqid, GetMemberById.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getMemberById.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getMemberById.FailuresCounter.incr()
          __stats_getMemberById.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getMemberById", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getMemberByMobile {
    val RequestsCounter = scopedStats.scope("getMemberByMobile").counter("requests")
    val SuccessCounter = scopedStats.scope("getMemberByMobile").counter("success")
    val FailuresCounter = scopedStats.scope("getMemberByMobile").counter("failures")
    val FailuresScope = scopedStats.scope("getMemberByMobile").scope("failures")
  }
  addFunction("getMemberByMobile", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getMemberByMobile.RequestsCounter.incr()
      val args = GetMemberByMobile.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getMemberByMobile(args.traceId, args.mobileTicket)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.memberber.rpc.domain.MemberResponse =>
        reply("getMemberByMobile", seqid, GetMemberByMobile.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getMemberByMobile.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getMemberByMobile.FailuresCounter.incr()
          __stats_getMemberByMobile.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getMemberByMobile", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_updateMemberStatus {
    val RequestsCounter = scopedStats.scope("updateMemberStatus").counter("requests")
    val SuccessCounter = scopedStats.scope("updateMemberStatus").counter("success")
    val FailuresCounter = scopedStats.scope("updateMemberStatus").counter("failures")
    val FailuresScope = scopedStats.scope("updateMemberStatus").scope("failures")
  }
  addFunction("updateMemberStatus", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_updateMemberStatus.RequestsCounter.incr()
      val args = UpdateMemberStatus.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.updateMemberStatus(args.traceId, args.memberId, args.status)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.memberber.rpc.domain.MemberBaseResponse =>
        reply("updateMemberStatus", seqid, UpdateMemberStatus.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_updateMemberStatus.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_updateMemberStatus.FailuresCounter.incr()
          __stats_updateMemberStatus.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("updateMemberStatus", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_updateNickName {
    val RequestsCounter = scopedStats.scope("updateNickName").counter("requests")
    val SuccessCounter = scopedStats.scope("updateNickName").counter("success")
    val FailuresCounter = scopedStats.scope("updateNickName").counter("failures")
    val FailuresScope = scopedStats.scope("updateNickName").scope("failures")
  }
  addFunction("updateNickName", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_updateNickName.RequestsCounter.incr()
      val args = UpdateNickName.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.updateNickName(args.traceId, args.memberId, args.nickName)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.memberber.rpc.domain.MemberBaseResponse =>
        reply("updateNickName", seqid, UpdateNickName.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_updateNickName.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_updateNickName.FailuresCounter.incr()
          __stats_updateNickName.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("updateNickName", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}